r = round(rnd*3)
if r == 0 then
playAudio "ballSound_trigger", "https://metaverse.my-domain.com/my-content/sounds/kick_ball.mp3", "oneshot", 1
else if r == 1 then
    play Audio "ballSound_trigger", "https://metaverse.my-domain.com/my-content/sounds/kick_ball2.mp3", "oneshot", 1
else if r == 2 then
    play Audio "ballSound_trigger", "https://metaverse.my-domain.com/my-content/sounds/kick_ball3.mp3", "oneshot", 1
end if